CREATE PROC [dbo].[FI_SP_ConsBeneficiario]
	@ID BIGINT,
	@IDCLIENTE BIGINT = NULL
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE (@IDCLIENTE IS NULL OR IDCLIENTE = @IDCLIENTE)
	ELSE
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID AND (@IDCLIENTE IS NULL OR IDCLIENTE = @IDCLIENTE)
END